#!/bin/zsh

git rev-parse --show-toplevel > /dev/null || {
    exit 1
}
cd $(git rev-parse --show-toplevel)

if [[ $# == 0 ]] 
then
    git commit -m "$(now) $(git cached | xargs)"
else
    git commit -m "$(now) $@ : $(git cached | xargs)"
fi
git push

cd -
