#!/bin/zsh

git_root_path=$(git rev-parse --show-toplevel)
if [[ $? > 0 ]]
then
    exit 1
fi
cd $git_root_path

if [[ $# == 0 ]] 
then
    git commit -m "$(now) $(git cached | xargs)"
else
    git commit -m "$(now) $* : $(git cached | xargs)"
fi
git push

cd -
