#!/usr/bin/python3

import sqlite3
import time

from utils import *


def update_git_repo(path: str) -> None:
    print(split_line)
    print("Git repo : {} from ".format(path), end="", flush=True)
    run_command("git -C {} remote -v | grep fetch | awk '{{print $2}}'".format(path))
    if run_command("git -C {} pull".format(path)):
        print("\rAborted.")
        try:
            time.sleep(2)
        except KeyboardInterrupt:
            print("\rAborted for all.")
            exit(1)


if __name__ == "__main__":
    parser = ArgumentParser(description="Update Git Repos")

    parser.add_argument("repos", type=str, default=[], nargs="*", help="repo paths")

    args = parser.parse_args()

    repos: List[str] = args.repos

    conn = sqlite3.connect(db_path)
    conn.execute("create table if not exists '{}' (path text unique)".format(git_repo_table_name))
    conn.commit()

    git_repo_paths = classify_repos(conn)

    conn.close()

    if repos:
        git_repo_paths = [path for repo in repos for path in git_repo_paths if re.search(repo, get_filename(path), re.IGNORECASE)]

    if not git_repo_paths:
        print("No git repo found.")
        exit(1)

    split_line = get_split_line()

    exec_all(update_git_repo, git_repo_paths, parallel=False)
