#!/usr/bin/python3

from argparse import ArgumentParser
import sqlite3

from utils import *


parser = ArgumentParser(description="Initialize brew formula root nodes")

args = parser.parse_args()

conn = sqlite3.connect(brew_root_db_path)
conn.execute("drop table if exists '{}'".format(brew_root_table_name))
conn.execute("create table if not exists '{}' (name text unique)".format(brew_root_table_name))
conn.commit()

all_nodes = read_all_nodes()
dependencies = read_dependencies()

for deps in dependencies.values():
    for dep in deps:
        if dep in all_nodes:
            all_nodes.remove(dep)

conn.executemany("insert into '{}' values (?)".format(brew_root_table_name),
                 [(node,) for node in all_nodes])
conn.commit()
conn.close()

print("Init root nodes into " + brew_root_db_path)
