#!/usr/bin/python3

import argparse
import sqlite3

from utils import *

# Doc for argparse : https://docs.python.org/3/library/argparse.html#the-add-argument-method

parser = argparse.ArgumentParser(description="Unset brew formula root nodes")

parser.add_argument("formula", type=str,
                    nargs="+", help="brew formula name")

args = parser.parse_args()

formula = args.formula

conn = sqlite3.connect(brew_root_db_path)
conn.execute("create table if not exists 'root-nodes' (name text unique)")
conn.commit()

root_nodes = read_root_nodes(conn)
all_nodes = read_all_nodes()

remove_list = auto_clean_root_nodes(conn, root_nodes, all_nodes)
formula = [f for f in formula if f not in remove_list]

if len(formula) > 0:
    for node in formula:
        if node not in all_nodes:
            print("Brew formula : " + node + " not found.")
            exit(1)
        if node not in root_nodes:
            print("Brew formula : " + node + " is not root node.")
            exit(1)

    print("Removing root nodes : " + to_string(formula))
    conn.executemany("delete from 'root-nodes' where name = ?",
                        [(node,) for node in formula])
    conn.commit()

    print("Running brew clean")
    run_command_s("brew clean")
else:
    print("Nothing to uninstall")

conn.close()
