#!/usr/bin/python3

import argparse
import os
import sqlite3

from utils import *


parser = argparse.ArgumentParser(description="Show brew formula root nodes")

args = parser.parse_args()

conn = sqlite3.connect(brew_root_db_path)
conn.execute("create table if not exists 'root-nodes' (name text unique)")
conn.commit()

root_nodes = read_root_nodes(conn)
all_nodes = read_all_nodes()

auto_clean_root_nodes(conn, root_nodes, all_nodes)

conn.close()

max_length = max([len(node) for node in root_nodes]) + 1
terminal_width = os.get_terminal_size().columns

item_in_line = int((terminal_width + 1) / max_length)

index = 0
for node in root_nodes:
    index += 1
    if index % item_in_line == 0:
        print(node.ljust(max_length - 1), end="")
        print()
    else:
        print(node.ljust(max_length), end="")

if index % item_in_line != 0:
    print()
