#!/usr/bin/python3

import sqlite3
import argparse
from utils import *

# Doc for argparse : https://docs.python.org/3/library/argparse.html#the-add-argument-method

parser = argparse.ArgumentParser(description="Set brew formula root nodes")

parser.add_argument("formula", type=str,
                    nargs="+", help="brew formula name")

args = parser.parse_args()

formula = args.formula

conn = sqlite3.connect(brew_root_db_path)
conn.execute("create table if not exists 'root-nodes' (name text unique)")
conn.commit()

root_nodes = read_root_nodes(conn)
all_nodes = read_all_nodes()

auto_clean_root_nodes(conn, root_nodes, all_nodes)

for f in formula:
    if f in root_nodes:
        print("Brew formula : " + f + " is already root node.")
        exit(1)

if check_formula_available(formula):
    exit(1)

print("Setting root nodes : " + to_string(formula))
conn.executemany("insert into 'root-nodes' values (?)",
                 [(node,) for node in formula])
conn.commit()
conn.close()

formula = [f for f in formula if f not in all_nodes]

if len(formula) > 0:
    print("Installing brew nodes")
    run_command("brew install --formula " + to_string(formula, " "))
else:
    print("Nothing to install")
