#!/bin/zsh

echo | sudo -S true &>/dev/null && {
    echo "Requires non sudo, otherwise EasyConnect.app will do something rubbish"
    exit 1
}

/Applications/EasyConnect.app/Contents/Resources/bin/EasyMonitor &> /dev/null &
/Applications/EasyConnect.app/Contents/MacOS/EasyConnect &> /dev/null &
