#!/bin/zsh

if [[ $# == 0 ]]
then
    echo -n Usage:" "
    cd /usr/local/bin
    echo k-* | sed 's/ /, /g' | sed 's/-/ /g'
    exit 1
fi

command -v s-$1 > /dev/null

if [[ $? == 0 ]]
then
    s-$@
else
    echo "s-$1: command not found"
    exit 1
fi
