#!/usr/bin/python3

from argparse import ArgumentParser

from utils import get_split_line


if __name__ == "__main__":
    parser = ArgumentParser(description="Get realpath of files")

    parser.add_argument("-s", "--splitter", type=str, default='-', help="pattern for split line")
    parser.add_argument("-e", "--end", action='store_true', help="do not print \\n at the end of line")
    parser.add_argument("-t", "--text", type=str, default=None, help="text in split line")

    args = parser.parse_args()

    splitter = args.splitter
    end = args.end
    text = args.text

    print(get_split_line(splitter, text), end='' if end else '\n')
