#!/usr/bin/python3

from utils import *


if __name__ == "__main__":
    parser = ArgumentParser(description="Join Strings")

    parser.add_argument("-s", "--splitter", type=str, default=", ", help="splitter of strings")
    parser.add_argument("-n", "--noend", action='store_true', help="do not print \\n at the end of line")
    parser.add_argument("files", type=str, default=[], nargs='*', help="input files")

    args = parser.parse_args()

    splitter: str = args.splitter
    noend: bool = args.noend
    files: List[str] = args.files

    if len(files) == 0:
        files.append("/dev/stdin")

    for file in files:
        with open(file, "r") as f:
            lines = (line.strip() for line in f.readlines())
            print(to_string(lines, splitter, True), end='' if noend else linesep)
