#!/usr/bin/python3

from argparse import ArgumentParser

from utils import to_string


if __name__ == "__main__":
    parser = ArgumentParser(description="Join strings")

    parser.add_argument("-s", "--splitter", type=str, default=", ", help="splitter of strings")
    parser.add_argument("-e", "--end", action='store_true', help="do not print \\n at the end of line")
    parser.add_argument("files", type=str, default=[], nargs='*', help="input files")

    args = parser.parse_args()

    splitter = args.splitter
    end = args.end
    files = args.files

    if len(files) == 0:
        files.append("/dev/stdin")

    for file in files:
        with open(file, "r") as f:
            lines = [line.strip() for line in f.readlines()]
            print(to_string(lines, splitter, True), end='' if end else '\n')
