#!/bin/zsh

if [[ $# == 0 ]]
then
    echo "Usage : $(cmds | grep "^cl-" | __str__ -n)"
    exit 1
fi

command -v cl-$1 > /dev/null

if [[ $? == 0 ]]
then
    cl-$@
else
    echo "cl-$1: command not found"
    exit 1
fi
