#!/usr/bin/python3

from argparse import ArgumentParser
import glob
import shutil
import sys

from utils import *


def remove(path: str):
    if os.path.isdir(path):
        try:
            shutil.rmtree(path)
        except FileNotFoundError as e:
            if not str(e.filename).startswith("._"):
                raise e
        except PermissionError as e:
            print("Requried permission to remove {}".format(path))
            exit(1)
    else:
        try:
            os.remove(path)
        except PermissionError as e:
            print("Requried permission to remove {}".format(path))
            exit(1)



if __name__ == "__main__":
    parser = ArgumentParser(description="Clean Directories")

    parser.add_argument("path", type=str, nargs="*", help="paths")

    args = parser.parse_args()

    path: List[str] = args.path

    cmd = sys.argv[0]

    for p in path:
        if shutil.which("{}-{}".format(cmd, p)):
            os.system("{}-{}".format(cmd, p))
        else:
            if not os.path.exists(p):
                raise FileNotFoundError("{} not found!".format(p))
            
            for pp in glob.glob(os.path.join(p, "*")):
                remove(pp)

            for pp in glob.glob(os.path.join(p, ".*")):
                remove(pp)
