#!/usr/bin/python3

from utils import *


if __name__ == "__main__":
    parser = ArgumentParser(description="Clean Dock Settings")

    parser.add_argument('-y', '--yes', action='store_true', help='comfirm to clean dock settings')

    args = parser.parse_args()

    yes: bool = args.yes

    if not yes:
        print("This script will clean dock settings.")
        print("Do you want to continue? Y/[N]: ", end="", flush=True)
        option = getchar()
        if option != os.linesep:
            print()
        if option.upper() != "Y":
            print("Aborted.")
            exit(1)
    
    print("Cleaning...")
    run_command([
            "defaults write com.apple.dock ResetLaunchPad -bool TRUE",
            "rm $HOME/Library/Application\ Support/Dock/*.db",
            "killall Dock"
        ])
