#!/usr/bin/python3

from utils import *


if __name__ == "__main__":
    parser = ArgumentParser(description="Clean System Privacy Settings")

    parser.add_argument('-y', '--yes', action='store_true', help='comfirm to clean system privacy settings')

    args = parser.parse_args()

    yes: bool = args.yes

    if not yes:
        print("This script will clean system privacy settings.")
        print("Do you want to continue? Y/[N]: ", end="", flush=True)
        option = getchar()
        if option != os.linesep:
            print()
        if option.upper() != "Y":
            print("Aborted.")
            exit(1)
    
    print("Cleaning...")
    run_command("tccutil reset All")
