#!/usr/bin/python3

from argparse import ArgumentParser
import shutil

from utils import *


if __name__ == "__main__":
    parser = ArgumentParser(description="Get realpath of files")

    parser.add_argument("path", type=str,
                        nargs="*", help="paths")

    args = parser.parse_args()

    path: List[str] = args.path

    for p in path:
        bin_path = shutil.which(p)
        if bin_path:
            print(bin_path)
        else:
            print(get_realpath(p))
