#!/usr/bin/python3

import argparse
import shutil

from utils import get_realpath


parser = argparse.ArgumentParser(description="Get realpath of files")

parser.add_argument("path", type=str,
                    nargs="*", help="paths")

args = parser.parse_args()

path = args.path

for p in path:
    bin_path = shutil.which(p)
    if bin_path:
        print(bin_path)
    else:
        print(get_realpath(p))
