#!/usr/bin/python3

from _curses import window
import curses
import pickle

from utils import *


def main(stdscr: window):
    last = None
    
    for i in range(0x110000):
        stdscr.clear()

        char = chr(i)
        try:
            stdscr.addstr(0, 0, char * num)
            charlen = (stdscr.getyx()[1] + num - 1) // num
        except:
            charlen = 0

        if charlen != last:
            length[char] = charlen
            last = charlen
            
    curses.endwin()


if __name__ == "__main__":
    parser = ArgumentParser(description="Update Char Length")

    parser.add_argument("-n", "--num", type=int, default=5, help="number of chars")

    args = parser.parse_args()

    num: int = args.num

    length = {}

    curses.wrapper(main)
    
    pickle.dump(length, open(charlen, "wb"))
