#!/usr/bin/python3

from utils import *


if __name__ == '__main__':
    parser = ArgumentParser(description="Get Commands")

    parser.add_argument("-n", "--name", type=str, default=None, help="name of command")

    args = parser.parse_args()

    name: str = args.name

    cmds = read_command("compgen -c")[1].split()

    if name:
        cmds = [c for c in cmds if re.search(name, c)]

    print(to_string(list(dict.fromkeys(cmds)), linesep, True))
