#!python3

from utils import *


if __name__ == "__main__":
    parser = ArgumentParser(description="Show Music Info")

    parser.add_argument("paths", type=str, default=[], nargs="*", help="music file path")

    args = parser.parse_args()

    try:
        import mutagen
    except ImportError:
        print("This script requires the 'mutagen' python libraries.")
        print("Please install and try again.")
        exit(1)

    paths: List[str] = args.paths

    if not paths:
        print("Please specify music file paths.")
        exit(1)

    try:
        info_table = (mutagen.File(path) for path in paths)
    except mutagen.MutagenError as e:
        raise e.args[0]

    info_table = ((get_file_fullname(info.filename), info.info.channels, info.info.sample_rate, info.info.length) for info in info_table)

    print(list_table(["File", "Channels", "Sample Rate", "Length"], info_table, ["{}", "{}", "{}", "{:.2f}"]), end="")
