#!/bin/zsh

OLDIFS=$IFS
IFS="
"

CONFIG=$HOME/.f2kconfig

RELOAD_REQUIRED=1

if [ -f $CONFIG ]
then
    CONFIGS=$(cat $CONFIG)
    if [[ $(echo $CONFIGS | xargs | lines) == 1 && -f $CONFIGS/.music ]]
    then
        MUSIC_BASE=$CONFIGS
        RELOAD_REQUIRED=0
    fi
fi

if [[ $RELOAD_REQUIRED == 1 ]]
then
    MUSIC_BASES=$(find $HOME -name ".music" 2> /dev/null)
    base_arr=()
    echo "$MUSIC_BASES" | while read line
    do
        rpath=$(realpath $line)
        if [[ ${base_arr[(ie)$rpath]} > ${#base_arr} ]]
        then
            base_arr+=$rpath
            break
        fi
    done
    if [[ ${#base_arr} == 0 ]]
    then
        echo "No music directories found."
        exit 1
    else
        if [[ ${#base_arr} == 1 ]]
        then
            MUSIC_BASE=$(dirname $base_arr[1])
            echo $MUSIC_BASE > $CONFIG
        else
            printf '%s\n' "${base_arr[@]}" > $CONFIG
            echo Require a music path or you should select one of your music paths into $CONFIG
            exit 1
        fi
    fi
fi

SONG="${MUSIC_BASE}/Song"
MUSIC="${MUSIC_BASE}/Music"
XW="${MUSIC_BASE}/XuWei"
F2K="${MUSIC_BASE}/foobar2000"
SONG_F2K="${F2K}/SONG.m3u8"
MUSIC_F2K="${F2K}/MUSIC.m3u8"

rm -rf ${F2K} 2> /dev/null
mkdir -p ${F2K}

echo "#" > ${SONG_F2K}
for i in `ls -1 ${SONG}/`
do
    if [ -f ${SONG}/$i ]
    then
        echo ${SONG}/$i >> ${SONG_F2K}
    fi
done

echo "#" > ${MUSIC_F2K}
for i in `ls -1 ${MUSIC}/`
do
    echo ${MUSIC}/$i >> ${MUSIC_F2K}
done

IFS=$OLDIFS
