#!/usr/bin/python3

from argparse import ArgumentParser
import os


if __name__ == "__main__":
    parser = ArgumentParser(description="Get Pid")

    args = parser.parse_args()

    print(os.getppid())
