#!/usr/bin/python3

from io import IOBase
import sys

from utils import *


def read_file(inputstream: IOBase) -> None:
    global byte
    try:
        while True:
            byte = inputstream.read(1)[0]
            if not no_linesep and byte == line_sep:
                print()
            else:
                print(format_int_base(byte, base).rjust(max_len, "0"), end=" ")
    except (EOFError, IndexError):
        pass


if __name__ == "__main__":
    parser = ArgumentParser(description="Read Byte Code from File")

    parser.add_argument("-b", "--base", type=int, default=16)
    parser.add_argument("-i", "--ignore-linesep", action="store_true")
    parser.add_argument("files", type=str, nargs="*", help="file to read")

    args = parser.parse_args()

    base: int = args.base
    no_linesep: bool = args.ignore_linesep
    files: List[str] = args.files

    max_len = byte_max_len(base)

    byte = line_sep

    if len(files) == 0:
        read_file(sys.stdin.buffer)
    else:
        for path in files:
            with open(path, "rb") as f:
                read_file(f)

    if no_linesep or byte != line_sep:
        print()
