#!/usr/bin/python3

import argparse

from utils import get_realpath


parser = argparse.ArgumentParser(description="Get realpath of files")

parser.add_argument("path", type=str,
                    nargs="*", help="paths")

args = parser.parse_args()

path = args.path

for p in path:
    print(get_realpath(p))
