#!/usr/bin/python3

from argparse import ArgumentParser

from utils import get_realpath


if __name__ == "__main__":
    parser = ArgumentParser(description="Get realpath of files")

    parser.add_argument("path", type=str,
                        nargs="*", help="paths")

    args = parser.parse_args()

    path = args.path

    for p in path:
        print(get_realpath(p))
