#!/usr/bin/python3

from argparse import ArgumentParser

from utils import *


if __name__ == "__main__":
    parser = ArgumentParser(description="Get Realpath of Files")

    parser.add_argument("path", type=str, nargs="*", help="paths")

    args = parser.parse_args()

    path: List[str] = args.path

    for p in path:
        print(get_realpath(p))
