#!/bin/zsh

sudo rm -rf /usr/local/texlive/ /Applications/TeX /Library/TeX /usr/local/share/doc/ghostscript /usr/local/share/ghostscript /usr/local/share/man/de
cd /usr/local/share/man/man1/
sudo rm -f dvipdf.1 eps2eps.1 gs.1 gsbj.1 gsdj.1 gsdj500.1 gslj.1 gslp.1 gsnd.1 pdf2dsc.1 pdf2ps.1 pf2afm.1 pfbtopfa.1 printafm.1 ps2ascii.1 ps2epsi.1 ps2pdf.1 ps2pdf12.1 ps2pdf13.1 ps2pdf14.1 ps2pdfwr.1 ps2ps.1
cd /usr/local/bin/
sudo rm -f dvipdf eps2eps gs gs-X11 gs-noX11 gsbj gsdj gsdj500 gslj gslp gsnd lprsetup.sh pdf2dsc pdf2ps pf2afm pfbtopfa pphs printafm ps2ascii ps2epsi ps2pdf ps2pdf12 ps2pdf13 ps2pdf14 ps2pdfwr ps2ps ps2ps2 unix-lpr.sh
