#!/bin/zsh

__splitline__ "brew update"
brew update || exit
__splitline__ "brew upgrade"
brew upgrade
__splitline__ 'brew upgrade $(brew list --cask) --cask'
brew upgrade $(brew list --cask) --cask

__splitline__ "conda update"
__splitline__ "base"
conda update -n base --all -y
environ=$(conda env list | grep py3 | awk '{print $1}')
__splitline__ "$environ"
conda update -n $environ --all -y
__splitline__ "conda clean"
conda clean -a -y
