#!/bin/zsh

echo '------------------ brew update -------------------'
brew update || exit
echo '------------------ brew upgrade ------------------'
brew upgrade
echo '----- brew upgrade `brew list --cask` --cask -----'
brew upgrade `brew list --cask` --cask

echo '------------------ conda update ------------------'
echo 'Environment : base'
conda update -n base --all -y
environ=$(conda env list | grep py3 | awk '{print $1}')
echo "Environment : $environ"
echo
conda update -n $environ --all -y
echo '------------------ conda clean -------------------'
conda clean -a -y
