#!/bin/zsh

if [ -e $HOME/OneDrive/Wallpapers/filelist ]
then
    rm -rf $HOME/OneDrive/Wallpapers/filelist
fi

files=($(ls $HOME/OneDrive/Wallpapers))

mkdir -p $HOME/OneDrive/Wallpapers/filelist

for file in $files
do
    filelist=$(ls -1 $HOME/OneDrive/Wallpapers/$file)
    if [[ $filelist != "" ]]
    then
        echo "$filelist" > "$HOME/OneDrive/Wallpapers/filelist/$file.txt"
    fi
done    
