#!/bin/zsh

if [[ $# == 0 ]]
then
    echo "Usage : $(cmds | grep "^k-" | __str__ -e)"
    exit 1
fi

command -v k-$1 > /dev/null

if [[ $? == 0 ]]
then
    k-$@
else
    echo "k-$1: command not found"
    exit 1
fi
