#!/bin/zsh

if [[ $# == 0 ]]
then
    echo "Usage : $(cmd -n "^update-" | __str__ -n)"
    exit 1
fi

command -v update-$1 > /dev/null || {
    echo "update-$1: command not found"
    exit 1
}

update-"$@"
