#!/bin/zsh

__splitblock__ -t "Update MacTex"
sudo tlmgr --repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet update --self
sudo tlmgr --repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet --machine-readable --persistent-downloads update --all
