#!/bin/zsh

__splitblock__ -t "conda update"
__exec__ -t "base" "conda update -n base --all -y"

environ=$(conda env list | grep py3 | awk '{print $1}')
__exec__ -t "$environ" "conda update -n $environ --all -y"

environs=$(conda env list | grep ^dev-)
for environ in $environs
do
    name=$(echo $environ | awk '{print $1}')
    loc=$(echo $environ | awk '{print $2}')
    __exec__ -t "conda pkgs for $name" "conda update -n $name --all -y"
    if [ -f $loc/upgrade-args ]
    then
        __exec__ -t "pip pkgs for $name" "$loc/bin/python -m pip install $(cat $loc/upgrade-args)"
    fi
done
__exec__ -t "conda clean" "conda clean -a -y"
