#!/bin/zsh

command -v tlmgr > /dev/null

if [[ $? == 0 ]]
then
    __splitblock__ -t "Update MacTex"
    sudo tlmgr --repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet update --machine-readable --persistent-downloads --self --all
else
    echo "MacTex not installed"
fi
