#!/usr/bin/python3

from argparse import ArgumentParser
import shutil

from utils import *


if __name__ == '__main__':
    parser = ArgumentParser(description="Update Something")

    parser.add_argument("-n", "--name", type=str, nargs="*", default=[], help="name of commands")
    parser.add_argument("cmd", type=str, nargs="*", help="command, ignored if name specified")

    args = parser.parse_args()

    name: List[str] = args.name
    cmd: List[str] = args.cmd

    if name:
        for n in name:
            if shutil.which("update-{}".format(n)):
                os.system("update-{}".format(n))
            else:
                raise FileNotFoundError("update-{}: command not found!".format(n))
    else:
        if not cmd:
            print("Usage : ", end='', flush=True)
            run_command_s("cmd -n '^update-' | __str__")
            exit(1)

        command = "update-" + to_string(cmd, ' ')

        run_command_s(command)
