#!python

try:
    import json
    import requests
except ImportError:
    print("This script requires the 'requests' and 'json' python libraries.")
    print("Please install them and try again.")
    exit(1)
obj = requests.get('http://ipinfo.io').json()
obj.pop('readme')
print(json.dumps(obj, indent=2))
