#!/usr/bin/python3

import json
from json import JSONDecodeError

from utils import *


def extract_duplicate(src1: Dict[Any, Any], src2: Dict[Any, Any]) -> Dict[Any, Any]:
    duplicate = {key: src1[key] for key in src1 if key in src2 and src1[key] == src2[key]}

    exec_all(src1.pop, duplicate.keys(), parallel=False)
    exec_all(src2.pop, duplicate.keys(), parallel=False)

    return duplicate


if __name__ == "__main__":
    parser = ArgumentParser(description="Get Public IP Address")

    args = parser.parse_args()

    res = exec_all(read_webpage, ["https://v4.ident.me/json", "https://v6.ident.me/json"])

    try:
        ipv4 = json.loads(res[0])
        ipv4.pop("postal")
    except JSONDecodeError:
        ipv4 = None

    try:
        ipv6 = json.loads(res[1])
        ipv6.pop("postal")
    except JSONDecodeError:
        ipv6 = None

    if not ipv4 and not ipv6:
        print("Error: Could not get IP Address")
        exit(1)

    if not ipv4:
        obj = {"v6": ipv6}
    
    elif not ipv6:
        obj = {"v4": ipv4}

    else:
        obj = {"v4": ipv4, "v6": ipv6, **extract_duplicate(ipv4, ipv6)}

    print(json.dumps(obj, indent=2))
