#!/bin/zsh

git_root_path=$(git rev-parse --show-toplevel)
if [[ $? > 0 ]]
then
    exit 1
fi
cd $git_root_path

git add . 
if [[ $# == 0 ]] 
then
    git commit -m "$(now) $(echo $(git st))"
else
    git commit -m "$(now) $(echo $(git st)) : $*"
fi
git push

cd -
