#!/bin/zsh

cd $(git rev-parse --show-toplevel) || exit 1
git add . 
if [[ $# == 0 ]] 
then
    git commit -m "$(now) $(echo $(git status -s))"
else
    git commit -m "$(now) $(echo $(git status -s)) : $*"
fi
git push
cd -
