#!/bin/zsh

if [[ $# > 0 ]]
then
    ip-$@
else
    p=$(which pcregrep)
    if [[ $? != 0 ]]
    then
        echo Require \"pcregrep\"
        exit 1
    fi

    ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*(inet |inet6 [^\n]+prefixlen 128)([^\n]|\n\t)*'
fi
