#!/bin/zsh

if [ "$#" -eq 0 ]
then
    num=$(ls -A | lines)
    echo "$num\t$pwd"
else
    file_num=0
    file_name="file:"
    for i in "$@"
    do
        i=$(realpath $i)
        if [ ! -d $i ]
        then
            file_num=$(($file_num + 1))
            file_name+=" $i"
        else
            num=$(ls -A $i | lines)
            echo "$num\t$i"
        fi
    done
    if [ $file_num -gt 1 ]
    then
        echo "$file_num\t$file_name"
    fi
fi
