#!python
import json
import requests


def read_from_web(url):
    """
    Reads the content of a web page and returns it as a dict.
    """
    try:
        response = requests.get(url)
        return response.json()
    except Exception:
        return None


js = read_from_web('http://ipinfo.io')
if js:
    js.pop('readme')
    print(json.dumps(js, indent=2))
else:
    print('Try again later.')
