#!/bin/zsh

files=$(find "$@" 2> /dev/null)

if [[ $(echo $files | lines) == 0 ]]
then
    echo No such files
    exit
fi

file_arr=()
file_name=""
echo $files | while read line
do
    if [[ ! "$line" =~ ^/System/Volumes/Data ]]
    then
        file_arr+="$line"
        file_name=$file_name$line$'\n'
    fi
done

echo -n $file_name
read -k 1 "opt?Do you want to remove above files? Y/[N]: "

if [[ ! "$opt" == "
" ]]
then
    echo
fi
if [[ ! "$opt" =~ ^[Yy]$ ]]
then
    echo Abort.
    exit 1
fi

rm -rf $file_arr
