#!/bin/zsh

for ((i = 1; i <= $#; i += 2))
do
    depth=$(eval echo '$'"$i")
    curr=$(eval echo '$'$(($i+1)))
    if [[ $curr == "" ]]
    then
        curr="."
    fi
    echo $curr:
    if [[ $depth =~ ^[0-9]+$ ]]
    then
        tree -L $depth $curr
    else
        echo $depth is not valid int value for depth
    fi
done
