#!/bin/zsh

echo '------------------ brew update -------------------'
brew update || exit
echo '------------------ brew upgrade ------------------'
brew upgrade
echo '----- brew upgrade `brew list --cask` --cask -----'
brew upgrade `brew list --cask` --cask
echo '---------------- conda update base ---------------'
conda update -n base --update-all -y
echo '---------------- conda update py39 ---------------'
conda update --update-all -y