#!/bin/zsh

echo '------------------ brew update -------------------'
brew update || exit
echo '------------------ brew upgrade ------------------'
brew upgrade
echo '----- brew upgrade `brew list --cask` --cask -----'
brew upgrade `brew list --cask` --cask

echo '------------------ conda update ------------------'
for i in $(conda env list | grep -v "^#" | awk '{print $1}')
do
    echo "$i :"
    conda update --update-all -n $i -y
done
