#!/bin/zsh

if [[ $# == 0 ]]
then
    echo "Usage : $(cmd -n "^proxy-" | __str__ -n)"
    exit 1
fi

command -v proxy-$1 &>/dev/null || {
    echo "proxy-$1: command not found"
    exit 1
}

proxy-$@
