#!/bin/zsh

# Recommend run as : eval $(proxy-on)
#               or : add to your ~/.zshrc as function

echo 'export http_proxy="http://127.0.0.1:1087"'
echo 'export https_proxy="http://127.0.0.1:1087"'
