#!/bin/zsh

if [[ $# == 0 ]]
then
    echo "Usage : $(cmd | grep "^proxy-" | __str__ -n)"
    exit 1
fi

command -v proxy-$1 &>/dev/null || {
    echo "proxy-$1 is not installed"
    exit 1
}

proxy-$@
